repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
    stages: [commit]
  - id: debug-statements
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3
    stages: [commit]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.261'
  hooks:
  - id: ruff
    stages: [commit]
    args: [ --fix, --exit-non-zero-on-fix ]
