on:
  push:
  pull_request:

jobs:
  container-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    container:
        image: ghcr.io/tiagocoutinho/v4l2py-py${{matrix.python-version}}:latest
    steps:
      - name: Test 
        run: pytest
